name: CI

on:
  workflow_dispatch:
    inputs:
      back_branch:
        description: 'The back branch'
        default: 'develop'
        required: false
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.back_branch.outputs.name }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: back_branch
        run: 'echo "name=$(echo ${{ inputs.name }}|tr -c [:alnum:] _|tr -s _|tr [:upper:] [:lower:])" >> "$GITHUB_OUTPUT"'
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
