name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - run: mkdir a && touch a/a.txt
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: ls -lha
