name: CI

on:
  workflow_dispatch:
    inputs:
      back_branch:
        description: 'The back branch'
        default: 'develop'
        required: false
        type: string
jobs:
  slugify:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      back_branch: ${{ steps.back_branch.outputs.name }}
      front_branch: ${{ steps.front_branch.outputs.name }}
    steps:
      - id: back_branch
        run: 'echo "name=$(echo -n ${{ inputs.back_branch }}|tr -c [:alnum:] _|tr -s _|tr [:upper:] [:lower:])" >> "$GITHUB_OUTPUT"'
      - id: front_branch
        run: echo "name=$(echo -n ${{ github.ref_name }}|tr -c [:alnum:] _|tr -s _|tr [:upper:] [:lower:])" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: slugify
    steps:
      - env:
          BACK_BRANCH: ${{needs.slugify.outputs.back_branch}}
          FRONT_BRANCH: ${{needs.slugify.outputs.front_branch}}
        run: echo "$BACK_BRANCH $FRONT_BRANCH"
